function [image]=loadNewImage()
    hwb=waitbar(0,'Load New image','Name','Please Wait');
    [filename,pathname]=uigetfile(...
        {'*.jpg;*.gif;*.png;*.tif;*.fig','MATLAB Files (*.jpg,*.gif,*.png,*.tif,*.fig)';...
        '*.jpg','JPEG Images (.jpg)';'*.gif','GIF Images (.gif)';...
        '*.png', 'GIF Images (.png)';'*.*','All Files (*.*)'},...
        'Select configuration or data');
    image = strcat(pathname,filename);
    close(hwb);
end